# Generated by Django 2.1.1 on 2018-09-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email address')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
            options={
                'verbose_name': 'email address',
                'verbose_name_plural': 'email addresses',
                'db_table': 'contacts_email_addresses',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'db_table': 'contacts_groups',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InstantMessenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im_account', models.CharField(max_length=100, verbose_name='im account')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('service', models.CharField(choices=[('aim', 'AIM'), ('msn', 'MSN'), ('icq', 'ICQ'), ('jabber', 'Jabber'), ('yahoo', 'Yahoo'), ('skype', 'Skype'), ('qq', 'QQ'), ('sametime', 'Sametime'), ('gadu-gadu', 'Gadu-Gadu'), ('google-talk', 'Google Talk'), ('other', 'Other')], default='other', max_length=11, verbose_name='service')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
            options={
                'verbose_name': 'instant messenger',
                'verbose_name_plural': 'instant messengers',
                'db_table': 'contacts_instant_messengers',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='middle name')),
                ('suffix', models.CharField(blank=True, max_length=50, null=True, verbose_name='suffix')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='nickname')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('photo', models.ImageField(blank=True, upload_to='contacts/person/', verbose_name='photo')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'db_table': 'contacts_people',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='number')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contacts.Person')),
            ],
            options={
                'verbose_name': 'phone number',
                'verbose_name_plural': 'phone numbers',
                'db_table': 'contacts_phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.TextField(max_length=200, verbose_name='occasion')),
                ('date', models.DateField(verbose_name='date')),
                ('every_year', models.BooleanField(default=True, verbose_name='every year')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialdates', to='contacts.Person')),
            ],
            options={
                'verbose_name': 'special date',
                'verbose_name_plural': 'special dates',
                'db_table': 'contacts_special_dates',
            },
        ),
        migrations.CreateModel(
            name='StreetAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(blank=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=200, verbose_name='province')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresss', to='contacts.Person')),
            ],
            options={
                'verbose_name': 'street address',
                'verbose_name_plural': 'street addresses',
                'db_table': 'contacts_street_addresses',
            },
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='contacts.Person')),
            ],
            options={
                'verbose_name': 'web site',
                'verbose_name_plural': 'web sites',
                'db_table': 'contacts_web_sites',
            },
        ),
        migrations.AddField(
            model_name='instantmessenger',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ims', to='contacts.Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='people',
            field=models.ManyToManyField(blank=True, to='contacts.Person', verbose_name='people'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contacts.Person'),
        ),
    ]
